from .telegram_users.views import *
from .tables.views import *
from .categories.views import *
from .products.views import *
from .orders.views import *
from .order_items.views import *
from .admin_user.views import *
from .public.views import *
from .telegram.views import *